src/protocole_base_repertoire/protocole/urls.py
from django.urls import path
from . import views

app_name = 'protocole'
urlpatterns = [
    path('', views.index, name='index'),
    path('simulation/', views.simulation, name='simulation'),
    path('reinitialisation_data/', views.reinitialisation_data, name='reinitialisation_data'),
    path('read_data/', views.read_data, name='read_data'),
    path('write_data/', views.write_data, name='write_data'),
]

src/protocole_base_repertoire/protocole_base_repertoire/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('protocole.urls'))
]

src/protocole_base_repertoire/protocole/models.py
from django.db import models

# Create your models here.

node_choice = (
    ('Home', 'Home'),
    ('Local', 'Local'),
    ('Remote', 'Remote'),
)

state_block = (
    ('1', 'Uncached'),
    ('2', 'Shared'),
    ('3', 'Modified'),
    ('4', 'Invalid'),
)

msg_type_choice = (
    ('1', "Read Miss"),
    ('2', "Write Miss"),
    ('3', "Data Value Reply"),
    ('4', "Invalidate"),
    ('5', "Fetch"),
    ('6', "Fetch/Invalidate"),
    ('7', "Data Write-Back"),
)

class Node(models.Model):
    name = models.CharField(max_length=30, choices=node_choice, default='Home')
    numero = models.IntegerField()

    def __str__(self) -> str:
        return f"Node {self.numero} - {self.name}"
    
    @property
    def node_string(self):
        return f"Node {self.numero}"
    
    @property
    def all_caches(self):
        return CacheNode.objects.filter(node=self).order_by('-id')
    
class MemoryBloc(models.Model):
    block_num = models.IntegerField()
    data = models.CharField(max_length=20, default='--')

    def __str__(self) -> str:
        return f"B{self.block_num}"
    
    @property
    def string_block(self) -> str:
        return f"B{self.block_num}"
    
class Directory(models.Model):
    bloc = models.OneToOneField(MemoryBloc, on_delete=models.CASCADE)
    state = models.CharField(max_length=30, choices=state_block, default='1')
    owner_bits = models.CharField(max_length=5)

    def __str__(self) -> str:
        return self.bloc
    
    @property
    def string_block(self) -> str:
        return f"B{self.bloc.block_num}"
    
    @property
    def state_directory(self):
        state = self.state
        if state == '1':
            return 'Uncached'
        elif state == '2':
            return 'Shared'
        elif state == '3':
            return 'Modified'
        elif state == '4':
            return 'Invalid'
        else:
            return state
    
class CacheNode(models.Model):
    node = models.ForeignKey(Node, on_delete=models.CASCADE)
    bloc = models.ForeignKey(MemoryBloc, on_delete=models.CASCADE)
    state_cache = models.CharField(max_length=20, choices=state_block)

    def __str__(self) -> str:
        return f"{self.node.name} B{self.bloc.block_num}"
    
    @property
    def state_cache_state(self):
        state = self.state_cache
        if state == '2':
            return 'Shared'
        elif state == '3':
            return 'Modified'
        elif state == '4':
            return 'Invalid'
        else:
            return state
    
class MessageSimulation(models.Model):
    type_message = models.CharField(max_length=30, choices=msg_type_choice)
    source = models.CharField(max_length=30)
    destination = models.CharField(max_length=30)
    content_msg = models.CharField(max_length=20)

    def __str__(self) -> str:
        return self.type_message
    
    @property
    def message(self):
        index = int(self.type_message)
        index -= 1
        return msg_type_choice[index][1]

src/protocole_base_repertoire/protocole/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *

def index(request):
    try:
        return render(request, 'protocole/index.html')
    except Exception as e:
        return HttpResponse(f"<h2>Error page ==> {e}</h2>")
    
def simulation(request):
    try:
        nodes = Node.objects.all()
        directory = Directory.objects.all()
        messages = MessageSimulation.objects.all().order_by('-id')
        blocks = MemoryBloc.objects.all()

        context = {
            'nodes': nodes,
            'directory': directory,
            'messages': messages,
            'blocks': blocks,
        }
        return render(request, 'protocole/simulation.html', context)
    except Exception as e:
        return HttpResponse(f"<h2>Error page ==> {e}</h2>")

# Generateur de message
def message_sender(type_message: str, source: str, dest: str, content_msg: str):
    MessageSimulation.objects.create(
        type_message=type_message,
        source=source,
        destination=dest,
        content_msg=content_msg,
    )

# Generateur de charer bits
def owner_bits(bits_list: list):
    if len(bits_list) >= 3:
        return '111'
    elif len(bits_list) == 2:
        if ['Local', 'Home'] == bits_list:
            return '110'
        if ['Local', 'Remote'] == bits_list:
            return '101'
        else:
            return '011'
    elif len(bits_list) == 1:
        if 'Local' in bits_list:
            return '100'
        if 'Home' in bits_list:
            return '010'
        else:
            return '001'
    else:
        return '000'

def read_data(request):
    try:
        if request.method == 'POST':
            node_id = int(request.POST.get('node'))
            block_id = int(request.POST.get('block'))

            node = Node.objects.get(id=node_id)
            block = Directory.objects.get(id=block_id)

            if block.state != '3':
                caches_node = CacheNode.objects.filter(node=node).filter(bloc=block.bloc)
                if caches_node.exists():
                    cache_node = caches_node.latest('id')
                    if cache_node.state_cache != '2': # 2: Shared
                        cache_node.state_cache = '2' # 2: Shared
                        cache_node.save()
                else:
                    CacheNode.objects.create(
                        node=node,
                        bloc=block.bloc,
                        state_cache='2',
                    )

                    node_home = Node.objects.get(numero=0)
                    MessageSimulation.objects.all().delete()
                    message_sender(
                        'Read Miss',
                        f"Cache {node.name}",
                        f"Repertoire {node_home.name}",
                        f"{node.node_string}, {block.string_block}",
                    )
                    message_sender(
                        'Data Value Reply',
                        f"Repertoire {node_home.name}",
                        f"Cache {node.name}",
                        content_msg=f"{block.bloc.data}",
                    )
            else:
                caches_all = CacheNode.objects.filter(state_cache='3') # 3: Modified
                cache_owner = None
                if caches_all.exists():
                    cache_owner = caches_all.latest('id')

                caches_node = CacheNode.objects.filter(node=node).filter(bloc=block.bloc)
                if caches_node.exists():
                    cache_node = caches_node.latest('id')
                    if cache_node.state_cache != '2': # 2: Shared
                        cache_node.state_cache = '2' # 2: Shared
                        cache_node.save()

                    node_home = Node.objects.get(numero=0)
                    if cache_owner is not None:
                        MessageSimulation.objects.all().delete()
                        message_sender(
                            'Fetch',
                            f"Repertoire {node_home.name}",
                            f"Cache {cache_owner.node.name}",
                            f"{block.string_block}",
                        )
                        message_sender(
                            'Data Write-Back',
                            f"Cache {cache_owner.node.name}",
                            f"Repertoire {node_home.name}",
                            f"{block.string_block}",
                        )
                        message_sender(
                            'Data Value Reply',
                            f"Repertoire {node_home.name}",
                            f"Cache {node.name}",
                            f"{block.string_block}",
                        )

                else:
                    CacheNode.objects.create(
                        node=node,
                        bloc=block.bloc,
                        state_cache='2', # 2: Shared
                    )

                    node_home = Node.objects.get(numero=0)
                    if cache_owner is not None:
                        MessageSimulation.objects.all().delete()
                        message_sender(
                            'Fetch',
                            f"Repertoire {node_home.name}",
                            f"Cache {cache_owner.node.name}",
                            f"{block.string_block}",
                        )
                        message_sender(
                            'Data Write-Back',
                            f"Cache {cache_owner.node.name}",
                            f"Repertoire {node_home.name}",
                            f"{block.string_block}",
                        )
                        message_sender(
                            'Data Value Reply',
                            f"Repertoire {node_home.name}",
                            f"Cache {node.name}",
                            f"{block.string_block}",
                        )
            
            caches = CacheNode.objects.filter(bloc=block.bloc)
            bits_list = []
            if caches.exists():
                for c in caches:
                    bits_list.append(c.node.name)

                block.state = '2' # 2: Shared
                block.owner_bits = owner_bits(bits_list)
                block.save()

            
            return redirect('protocole:simulation')
    except Exception as e:
        return HttpResponse(f"<h2>Error page ==> {e}</h2>")
    
def write_data(request):
    try:
        if request.method == 'POST':
            node_id = int(request.POST.get('node'))
            block_id = int(request.POST.get('block'))
            data = str(request.POST.get('data_send'))

            if data != '':
                node = Node.objects.get(id=node_id)
                block = Directory.objects.get(id=block_id)

                block_memory = MemoryBloc.objects.get(id=block.bloc.id)
                block_memory.data = data
                block_memory.save()

                node_home = Node.objects.get(numero=0)

                if block.state == '1': # 1: Uncached
                    MessageSimulation.objects.all().delete()
                    message_sender(
                        'Write Miss',
                        f"Cache {node.name}",
                        f"Repertoire {node_home.name}",
                        f"{node.node_string}, {block.string_block}",
                    )
                    message_sender(
                        'Data Value Reply',
                        f"Repertoire {node_home.name}",
                        f"Cache {node.name}",
                        f"{block.string_block}",
                    )
                    CacheNode.objects.create(
                        node=node,
                        bloc=block.bloc,
                        state_cache='3', # 3: Modified
                    )
                    if node.name == 'Home':
                        bit_shared = '100'
                    elif node.name == 'Local':
                        bit_shared = '010'
                    elif node.name == 'Remote':
                        bit_shared = '001'
                    
                    block.state = '3' # 3: Modified
                    block.owner_bits = bit_shared
                    block.save()

                elif block.state == '2': # 2: Shared
                    MessageSimulation.objects.all().delete()
                    message_sender(
                        'Data Value Reply',
                        f"Repertoire {node_home.name}",
                        f"Cache {node.name}",
                        f"{block.bloc.data}",
                    )

                    block_in_chached = CacheNode.objects.filter(bloc=block_memory)
                    if block_in_chached.exists():
                        for block_cache in block_in_chached:
                            message_sender(
                                'Invalidate',
                                f"Repertoire {node_home.name}",
                                f"Cache {block_cache.node.name}",
                                f"{block.string_block}",
                            )
                            block_cache.state_cache = '4' # 4: Invalid
                            block_cache.save()
                    
                    proprio = block_in_chached.filter(node=node)
                    if proprio.exists():
                        cached = proprio.latest('id')
                        cached.state_cache = '3' # 3: Modified
                        cached.save()

                    else:
                        CacheNode.objects.create(
                            node=node,
                            bloc=block.bloc,
                            state_cache='3', # 3: Modified
                        )

                    if node.name == 'Home':
                        bit_shared = '100'
                    elif node.name == 'Local':

src/protocole_base_repertoire/protocole/templates/protocole/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>HOME</title>
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_home.css' %}">
    <style>
        #intro {
            background-image: url("/static/images/bg-1.jpg");
            height: 100vh;
        }
        #intro1 {
            background-image: url("/static/images/bg-1.jpg");
        }
    </style>
</head>
<body>
    <div id="intro" class="bg-image shadow-2-strong">
        <div class="mask" style="background-color: rgba(0, 0, 0, 0.6);">
            <div class="container d-flex align-items-center justify-content-center text-center h-100">
                <div class="text-white">
                    <h2 class="mb-3 title">
                        COURS DES SYSTEMES A MULTIPROCESSEURS ET MACHINES PARALLELES
                    </h2>
                    <div class="row">
                        <div class="col">
                            <div class="card text-dark">
                                <div class="card-body text-start">
                                    <ul class="list-group list-group-light">
                                        <li class="list-group-item d-flex justify-content-between align-items-center">
                                            <div>
                                                <div class="fw-bold text-uppercase">Noms:</div>
                                                <div class="text-muted">MUGISHO CIRINDYE Frederick</div>
                                            </div>
                                        </li>
                                        <li class="list-group-item d-flex justify-content-between align-items-center">
                                            <div>
                                                <div class="fw-bold text-uppercase">Promotion:</div>
                                                <div class="text-muted">Tech 1 Génie Informatique / FSTA</div>
                                            </div>
                                        </li>
                                        <li class="list-group-item d-flex justify-content-between align-items-center">
                                            <div>
                                                <div class="fw-bold text-uppercase">Intitulé du projet</div>
                                                <div class="text-muted">Simulation du protocole basé sur le répertoire</div>
                                            </div>
                                        </li>
                                        <li class="list-group-item d-flex justify-content-between align-items-center">
                                            <div>
                                                <div class="fw-bold text-uppercase">Enseignant</div>
                                                <div class="text-muted">Msc KAMBALE WAMUHINDO Abednego</div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <img src="{% static 'images/image.jpg' %}" height="385" width="500">
                        </div>
                    </div>
                    <a class="btn btn-success btn-login btn-lg m-4" href="{% url "protocole:simulation" %}" role="button">
                        Commencer
                    </a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

src/protocole_base_repertoire/protocole/templates/protocole/simulation.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>HOME</title>
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_home.css' %}">
    
</head>
<body style="background-color: rgba(0, 0, 0, 0.8);">
    <div class="container-fluid mb-3">
        <h1 class="text-center title mt-3">SIMULATION DU PROTOCOLE</h1>
        <hr class="text-white">
        <div class="row g-4">
            {% for node in nodes %}
                <div class="col">
                    <div class="card">
                        <div class="card-header fw-bolder text-uppercase text-center text-uppercase">{{node}}</div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-sm">
                                    <thead>
                                        <tr>
                                            <th class="fw-bolder text-uppercase">Block</th>
                                            <th class="fw-bolder text-uppercase">Data</th>
                                            <th class="fw-bolder text-uppercase">Etat</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% if node.all_caches %}
                                            {% for cache in node.all_caches %}
                                                {% if cache.state_cache == '4' %}
                                                    <tr class="text-danger">
                                                        <td>{{cache.bloc}}</td>
                                                        <td>--</td>
                                                        <td>{{cache.state_cache_state}}</td>
                                                    </tr>
                                                {% else %}
                                                    <tr>
                                                        <td>{{cache.bloc}}</td>
                                                        <td>{{cache.bloc.data}}</td>
                                                        <td>{{cache.state_cache_state}}</td>
                                                    </tr>
                                                {% endif %}
                                            {% endfor %}
                                        {% else %}
                                            <tr>
                                                <td class="text-danger">Cache vide</td>
                                                <td></td>
                                                <td></td>
                                            </tr>
                                        {% endif %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <hr class="text-white">
        <div class="card">
            <div class="card-body">
                <form action="" method="post" enctype="multipart/form-data" id="form_command">
                    <div class="">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col">
                                <select name="node" class="form-control form-select custom-select">
                                    {% for node in nodes %}
                                        <option value={{node.id}}>{{node.node_string}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col">
                                <select name="block" class="form-control form-select custom-select">
                                    {% for block in directory %}
                                        <option value={{block.id}}>{{block.bloc}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col">
                                <input type="text" id="data_send" placeholder="Data write" class="form-control" name="data_send">
                            </div>
                            <div class="col d-flex gap-2">
                                <button onclick="read_data()" type="button" class="btn btn-secondary btn-sm">Lire</button>
                                <button onclick="write_data()" type="button" class="btn btn-success btn-sm">Ecrire</button>
                            </div>
                            <div class="col">
                                <a href="{% url "protocole:reinitialisation_data" %}" class="btn btn-primary">
                                    Reset
                                </a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <hr class="text-white">
        <div class="row g-4">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header fw-bolder text-uppercase">Repertoire</div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-sm">
                                <thead>
                                    <tr>
                                        <th class="fw-bolder text-uppercase">Block</th>
                                        <th class="fw-bolder text-uppercase">Etat</th>
                                        <th class="fw-bolder text-uppercase">Sharer bits</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for dir in directory %}
                                        <tr>
                                            <td>{{dir.bloc}}</td>
                                            <td>{{dir.state_directory}}</td>
                                            <td>{{dir.owner_bits}}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header fw-bolder text-uppercase">Messages</div>
                    <div class="card-body">
                        <p class="alert alert-info">On supprimer les messages précedents à chaque requete, pour mieux voir !</p>
                        <div class="table-responsive">
                            <table class="table table-sm">
                                <thead>
                                    <tr>
                                        <th class="fw-bolder text-uppercase">Type message</th>
                                        <th class="fw-bolder text-uppercase">Source</th>
                                        <th class="fw-bolder text-uppercase">Destination</th>
                                        <th class="fw-bolder text-uppercase">Contenu</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if messages %}
                                        {% for msg in messages %}
                                            {% if msg.type_message == 'Read Miss' or msg.type_message == 'Write Miss' or msg.type_message == 'Fetch/Invalidate' or msg.type_message == 'Invalidate' %}
                                                <tr class="text-danger">
                                                    <td>{{msg.type_message}}</td>
                                                    <td>{{msg.source}}</td>
                                                    <td>{{msg.destination}}</td>
                                                    <td>{{msg.content_msg}}</td>
                                                </tr>
                                            {% else %}
                                                <tr>
                                                    <td>{{msg.type_message}}</td>
                                                    <td>{{msg.source}}</td>
                                                    <td>{{msg.destination}}</td>
                                                    <td>{{msg.content_msg}}</td>
                                                </tr>
                                            {% endif %}
                                        {% endfor %}
                                    {% else %}
                                        <tr>
                                            <td class="text-danger">Aucun message</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                    {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        function read_data(){
            const form_command = document.getElementById('form_command');
            console.log(form_command);
            form_command.action = "{% url 'protocole:read_data' %}";
            form_command.submit();
        }
    </script>
    <script>
        function write_data(){
            const form_command = document.getElementById('form_command');
            const data_send = document.getElementById('data_send');
            console.log(data_send.value);
            form_command.action = "{% url 'protocole:write_data' %}";
            form_command.submit();
            
        }
    </script>
</body>
</html>